### ISSUE TITLE
Implement as reformatter

### ISSUE THREAD

**Issue by scop** [luckysori/dprint-fmt#1]
To make this mode even fewer lines of code than it already is, and to gain a bunch of features while doing so, I suggest redoing this as a reformatter, see https://github.com/purcell/emacs-reformatter

Some examples:
- https://github.com/purcell/emacs-shfmt
- https://github.com/wyuenho/emacs-python-isort

**Comment by luckysori** [comment]
That's a great idea! I wasn't aware of that project, so thanks for the tip :D

The `dprint-mode` I put together here is barely functional anyway (the on-save hook doesn't work haha), so I think rewriting it using that library is the way to go.

**Comment by luckysori** [comment]
Looks like something as simple as this does the trick:

```lisp
;; -*- lexical-binding: t; -*-

(defcustom dprint-fmt-command "dprint"
  "Command used for reformatting."
  :type 'string)

(reformatter-define dprint-fmt
  :program dprint-fmt-command
  :args (list "fmt" "--stdin" input-file)
  :input-file (reformatter-temp-file-in-current-directory)
  :lighter " dprint-fmt")

(provide 'dprint-fmt)
```

**Comment by luckysori** [comment]
Current master uses `reformatter.el`. Thanks for the suggestion!
